### ISSUE TITLE
use enqueue redis transport error 

### ISSUE THREAD

**Issue by BinZhiZhu** [php-enqueue/enqueue-dev#1153]
when we used standard redis instance, consumer process everything is ok,but we upgraded redis instance to cluster instance,we observed consumer process, we found some error as follow:

```
接受消息发生错误Predis\Response\ServerException: CROSSSLOT Keys in request don't hash to the same slot in /home/wwwroot/live-ecs.escase.cn/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /home/wwwroot/live-ecs.escase.cn/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\ServerEval), Object(Predis\Response\Error))
#1 /home/wwwroot/live-ecs.escase.cn/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\ServerEval))
#2 [internal function]: Predis\Client->__call('eval', Array)
#3 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/PRedis.php(61): call_user_func_array(Array, Array)
#4 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumerHelperTrait.php(112): Enqueue\Redis\PRedis->eval('-- Get all of t...', Array, Array)
#5 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumerHelperTrait.php(36): Enqueue\Redis\RedisConsumer->migrateExpiredMessages(Array)
#6 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumer.php(76): Enqueue\Redis\RedisConsumer->receiveMessage(Array, 2, 300)
#7 /home/wwwroot/live-ecs.escase.cn/app/libs/core/components/QueueContainer.php(228): Enqueue\Redis\RedisConsumer->receive(2)
#8 /home/wwwroot/live-ecs.escase.cn/app/commands/queue/NormalService.php(75): pengpai\libs\core\components\QueueContainer->consume(Object(Enqueue\Redis\RedisDestination), 2000, Object(pengpai\commands\DaemonController))
#9 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(2393): pengpai\commands\queue\NormalService->pengpai\commands\queue\{closure}(Object(Workerman\Worker))
#10 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1541): Workerman\Worker->run()
#11 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#12 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#13 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
#14 /home/wwwroot/live-ecs.escase.cn/app/commands/DaemonController.php(134): Workerman\Worker::runAll()
#15 [internal function]: pengpai\commands\DaemonController->actionService('queue-normal', 'start')
#16 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Controller.php(187): yii\base\InlineAction->runWithParams(Array)
#18 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Controller.php(179): yii\base\Controller->runAction('service', Array)
#19 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Module.php(532): yii\console\Controller->runAction('service', Array)
#20 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Application.php(180): yii\base\Module->runAction('daemon/service', Array)
#21 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Application.php(147): yii\console\Application->runAction('daemon/service', Array)
#22 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Application.php(388): yii\console\Application->handleRequest(Object(pengpai\components\console\Request))
#23 /home/wwwroot/live-ecs.escase.cn/app/components/console/Application.php(24): yii\base\Application->run()
#24 /home/wwwroot/live-ecs.escase.cn/yii(9): pengpai\components\console\Application->run()
#25 {main}

Next Enqueue\Redis\ServerException: eval command has failed in /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/PRedis.php:63
Stack trace:
#0 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumerHelperTrait.php(112): Enqueue\Redis\PRedis->eval('-- Get all of t...', Array, Array)
#1 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumerHelperTrait.php(36): Enqueue\Redis\RedisConsumer->migrateExpiredMessages(Array)
#2 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumer.php(76): Enqueue\Redis\RedisConsumer->receiveMessage(Array, 2, 300)
#3 /home/wwwroot/live-ecs.escase.cn/app/libs/core/components/QueueContainer.php(228): Enqueue\Redis\RedisConsumer->receive(2)
#4 /home/wwwroot/live-ecs.escase.cn/app/commands/queue/NormalService.php(75): pengpai\libs\core\components\QueueContainer->consume(Object(Enqueue\Redis\RedisDestination), 2000, Object(pengpai\commands\DaemonController))
#5 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(2393): pengpai\commands\queue\NormalService->pengpai\commands\queue\{closure}(Object(Workerman\Worker))
#6 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1541): Workerman\Worker->run()
#7 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#8 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#9 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
#10 /home/wwwroot/live-ecs.escase.cn/app/commands/DaemonController.php(134): Workerman\Worker::runAll()
#11 [internal function]: pengpai\commands\DaemonController->actionService('queue-normal', 'start')
#12 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Controller.php(187): yii\base\InlineAction->runWithParams(Array)
#14 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Controller.php(179): yii\base\Controller->runAction('service', Array)
#15 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Module.php(532): yii\console\Controller->runAction('service', Array)
#16 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Application.php(180): yii\base\Module->runAction('daemon/service', Array)
#17 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Application.php(147): yii\console\Application->runAction('daemon/service', Array)
#18 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Application.php(388): yii\console\Application->handleRequest(Object(pengpai\components\console\Request))
#19 /home/wwwroot/live-ecs.escase.cn/app/components/console/Application.php(24): yii\base\Application->run()
#20 /home/wwwroot/live-ecs.escase.cn/yii(9): pengpai\components\console\Application->run()
#21 {main}2021-03-25 16:53:08
接受消息发生错误Predis\Response\ServerException: CROSSSLOT Keys in request don't hash to the same slot in /home/wwwroot/live-ecs.escase.cn/vendor/predis/predis/src/Client.php:370
Stack trace:
#0 /home/wwwroot/live-ecs.escase.cn/vendor/predis/predis/src/Client.php(335): Predis\Client->onErrorResponse(Object(Predis\Command\ServerEval), Object(Predis\Response\Error))
#1 /home/wwwroot/live-ecs.escase.cn/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\ServerEval))
#2 [internal function]: Predis\Client->__call('eval', Array)
#3 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/PRedis.php(61): call_user_func_array(Array, Array)
#4 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumerHelperTrait.php(112): Enqueue\Redis\PRedis->eval('-- Get all of t...', Array, Array)
#5 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumerHelperTrait.php(36): Enqueue\Redis\RedisConsumer->migrateExpiredMessages(Array)
#6 /home/wwwroot/live-ecs.escase.cn/vendor/enqueue/redis/RedisConsumer.php(76): Enqueue\Redis\RedisConsumer->receiveMessage(Array, 2, 300)
#7 /home/wwwroot/live-ecs.escase.cn/app/libs/core/components/QueueContainer.php(228): Enqueue\Redis\RedisConsumer->receive(2)
#8 /home/wwwroot/live-ecs.escase.cn/app/commands/queue/NormalService.php(75): pengpai\libs\core\components\QueueContainer->consume(Object(Enqueue\Redis\RedisDestination), 2000, Object(pengpai\commands\DaemonController))
#9 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(2393): pengpai\commands\queue\NormalService->pengpai\commands\queue\{closure}(Object(Workerman\Worker))
#10 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1541): Workerman\Worker->run()
#11 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1371): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#12 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(1345): Workerman\Worker::forkWorkersForLinux()
#13 /home/wwwroot/live-ecs.escase.cn/vendor/workerman/workerman/Worker.php(546): Workerman\Worker::forkWorkers()
#14 /home/wwwroot/live-ecs.escase.cn/app/commands/DaemonController.php(134): Workerman\Worker::runAll()
#15 [internal function]: pengpai\commands\DaemonController->actionService('queue-normal', 'start')
#16 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#17 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Controller.php(187): yii\base\InlineAction->runWithParams(Array)
#18 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Controller.php(179): yii\base\Controller->runAction('service', Array)
#19 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Module.php(532): yii\console\Controller->runAction('service', Array)
#20 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Application.php(180): yii\base\Module->runAction('daemon/service', Array)
#21 /home/wwwroot/live-ecs.escase.cn/libs/yii2/console/Application.php(147): yii\console\Application->runAction('daemon/service', Array)
#22 /home/wwwroot/live-ecs.escase.cn/libs/yii2/base/Application.php(388): yii\console\Application->handleRequest(Object(pengpai\components\console\Request))
#23 /home/wwwroot/live-ecs.escase.cn/app/components/console/Application.php(24): yii\base\Application->run()
#24 /home/wwwroot/live-ecs.escase.cn/yii(9): pengpai\components\console\Application->run()
#25 {main}
```

Doesn't it support redis clusters?

**Comment by BinZhiZhu** [comment]
Look like a problem with redis extension difference, need to specify redis scheme_extensions ? phpredis or predis？
