### ISSUE TITLE
[Feature Request/Bug] Laravel Horizon support for `enqueue/laravel-queue`

### ISSUE THREAD

**Issue by ThaDaVos** [php-enqueue/enqueue-dev#1181]
When trying to use the package with Laravel Horizon I am getting the follow error:
```log
local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Enqueue\LaravelQueue\AmqpQueue::readyNow() in /var/www/html/vendor/kinsolee/horizon-lumen/src/AutoScaler.php:80
Stack trace:
#0 /var/www/html/vendor/illuminate/support/Collection.php(685): Laravel\Horizon\AutoScaler->Laravel\Horizon\{closure}()
#1 /var/www/html/vendor/kinsolee/horizon-lumen/src/AutoScaler.php(86): Illuminate\Support\Collection->mapWithKeys()
#2 /var/www/html/vendor/kinsolee/horizon-lumen/src/AutoScaler.php(49): Laravel\Horizon\AutoScaler->timeToClearPerQueue()
#3 /var/www/html/vendor/kinsolee/horizon-lumen/src/Supervisor.php(343): Laravel\Horizon\AutoScaler->scale()
#4 /var/www/html/vendor/kinsolee/horizon-lumen/src/Supervisor.php(300): Laravel\Horizon\Supervisor->autoScale()
#5 /var/www/html/vendor/kinsolee/horizon-lumen/src/Supervisor.php(267): Laravel\Horizon\Supervisor->loop()
#6 /var/www/html/vendor/kinsolee/horizon-lumen/src/Console/SupervisorCommand.php(92): Laravel\Horizon\Supervisor->monitor()
#7 /var/www/html/vendor/kinsolee/horizon-lumen/src/Console/SupervisorCommand.php(67): Laravel\Horizon\Console\SupervisorCommand->start()
#8 /var/www/html/vendor/illuminate/container/BoundMethod.php(36): Laravel\Horizon\Console\SupervisorCommand->handle()
#9 /var/www/html/vendor/illuminate/container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#10 /var/www/html/vendor/illuminate/container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#11 /var/www/html/vendor/illuminate/container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/illuminate/container/Container.php(590): Illuminate\Container\BoundMethod::call()
#13 /var/www/html/vendor/illuminate/console/Command.php(134): Illuminate\Container\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#15 /var/www/html/vendor/illuminate/console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(1009): Illuminate\Console\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#19 /var/www/html/vendor/illuminate/console/Application.php(93): Symfony\Component\Console\Application->run()
#20 /var/www/html/vendor/laravel/lumen-framework/src/Console/Kernel.php(115): Illuminate\Console\Application->run()
#21 /var/www/html/artisan(35): Laravel\Lumen\Console\Kernel->handle()
#22 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Enqueue\\LaravelQueue\\AmqpQueue::readyNow() at /var/www/html/vendor/kinsolee/horizon-lumen/src/AutoScaler.php:80)
[stacktrace]
#0 /var/www/html/vendor/illuminate/support/Collection.php(685): Laravel\\Horizon\\AutoScaler->Laravel\\Horizon\\{closure}()
#1 /var/www/html/vendor/kinsolee/horizon-lumen/src/AutoScaler.php(86): Illuminate\\Support\\Collection->mapWithKeys()
#2 /var/www/html/vendor/kinsolee/horizon-lumen/src/AutoScaler.php(49): Laravel\\Horizon\\AutoScaler->timeToClearPerQueue()
#3 /var/www/html/vendor/kinsolee/horizon-lumen/src/Supervisor.php(343): Laravel\\Horizon\\AutoScaler->scale()
#4 /var/www/html/vendor/kinsolee/horizon-lumen/src/Supervisor.php(300): Laravel\\Horizon\\Supervisor->autoScale()
#5 /var/www/html/vendor/kinsolee/horizon-lumen/src/Supervisor.php(267): Laravel\\Horizon\\Supervisor->loop()
#6 /var/www/html/vendor/kinsolee/horizon-lumen/src/Console/SupervisorCommand.php(92): Laravel\\Horizon\\Supervisor->monitor()
#7 /var/www/html/vendor/kinsolee/horizon-lumen/src/Console/SupervisorCommand.php(67): Laravel\\Horizon\\Console\\SupervisorCommand->start()
#8 /var/www/html/vendor/illuminate/container/BoundMethod.php(36): Laravel\\Horizon\\Console\\SupervisorCommand->handle()
#9 /var/www/html/vendor/illuminate/container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/html/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#11 /var/www/html/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#12 /var/www/html/vendor/illuminate/container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#13 /var/www/html/vendor/illuminate/console/Command.php(134): Illuminate\\Container\\Container->call()
#14 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#15 /var/www/html/vendor/illuminate/console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#16 /var/www/html/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run()
#17 /var/www/html/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand()
#18 /var/www/html/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun()
#19 /var/www/html/vendor/illuminate/console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#20 /var/www/html/vendor/laravel/lumen-framework/src/Console/Kernel.php(115): Illuminate\\Console\\Application->run()
#21 /var/www/html/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle()
#22 {main}
"} 
```

**Comment by makasim** [comment]
PR is welcome.
