### ISSUE TITLE
[FS] Maximum function nesting level of '256' reached

### ISSUE THREAD

**Issue by eugenekurasov** [php-enqueue/enqueue-dev#327]
composer show | grep "enqueue":
```
enqueue/async-event-dispatcher           0.8.12               
enqueue/enqueue                          0.8.13               
enqueue/enqueue-bundle                   0.8.13               
enqueue/fs                               0.8.12               
enqueue/null                             0.8.12               
enqueue/sqs                              0.8.12  
```
Config:
```
enqueue:
    transport:
        default: 'file:////var/queue' # Path has been changed
```

Command
```
bin/console enqueue:consume --message-limit=1 -vvv
```

Stack trace
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Maximum function nesting level of '256' reached, aborting! in /app/api/vendor/enqueue/fs/FsConsumer.php:211
Stack trace:
#0 /app/api/vendor/enqueue/fs/FsConsumer.php(211): fseek(Resource id #3234, -15424, 2)
#1 /app/api/vendor/enqueue/fs/FsConsumer.php(221): Enqueue\Fs\FsConsumer->readFrame(Resource id #3234, 241)
#2 /app/api/vendor/enqueue/fs/FsConsumer.php(221): Enqueue\Fs\FsConsumer->readFrame(Resource id #3234, 240)
#3 /app/api/vendor/enqueue/fs/FsConsumer.php(221): Enqueue\Fs\FsConsumer->readFrame(Resource id #3234, 239)
#4 /app/api/vendor/enqueue/fs/FsConsumer.php(221): Enqueue\Fs\FsConsumer->readFrame(Resource id #3234, 238)
#5 /app/api/vendor/enqueue/fs/FsConsumer.php(221): Enqueue\Fs\FsConsumer->readFrame(Resource id #3234, 237)
#6 /app/api/vendor/enqueue/fs/FsConsumer.php(221): Enqueue\Fs\FsConsumer->readFrame(Resource id #3234, 236)
#7 /app/api/vendor/enqueue/fs/FsConsumer.php(221): Enqueue\Fs\FsConsumer->readFrame(Resource id #3234, 2 in /app/api/vendor/enqueue/fs/FsConsumer.php on line 211
```
Message is more than 18 000 length.

**Comment by makasim** [comment]
What is in the file ?

**Comment by eugenekurasov** [comment]
XML

**Comment by makasim** [comment]
Could you post it?

**Comment by eugenekurasov** [comment]
I was replace xml content by simple text(length has been saved) [test.txt](https://github.com/php-enqueue/enqueue-dev/files/1625897/test.txt)

**Comment by makasim** [comment]
I wrote a test and used your example file. It failed with exception

```
.....E                                                              6 / 6 (100%)

Time: 63 ms, Memory: 4.00MB

There was 1 error:

1) Enqueue\Fs\Tests\Functional\FsConsumerTest::testBug327
LogicException: The frame could start from either " " or "|". The malformed frame starts with "d".

/Users/makasim/projects/enqueue/enqueue-sandbox/dev/pkg/fs/FsConsumer.php:125
/Users/makasim/projects/enqueue/enqueue-sandbox/dev/pkg/fs/FsContext.php:121
/Users/makasim/projects/enqueue/enqueue-sandbox/dev/pkg/fs/FsConsumer.php:155
/Users/makasim/projects/enqueue/enqueue-sandbox/dev/pkg/fs/Tests/Functional/FsConsumerTest.php:195
```

**Comment by eugenekurasov** [comment]
Hi,
What value of xdebug.max_nesting_level ?

**Comment by makasim** [comment]
I dont use filesystem transport at all. The solution would be to replace recursive method call with a while cycle.

**Comment by eugenekurasov** [comment]
Hi, file is can have invalid message, I am created file with very long message so reproduce this bug.
Filesystem is used in dev mode.

**Comment by makasim** [comment]
This issue is on my list, though, not at the top. I'm currently heavily busy with my work errands.

However, I'd really appreciate some sponsorship to work on this task. If anybody interested, feels free to pm me (my email address is available on my GitHub profile page).

**Comment by makasim** [comment]
PR is welcome

**Comment by afilina** [comment]
@makasim How much sponsorship to fix this specific bug?

**Comment by afilina** [comment]
@makasim How much sponsorship to fix this specific issue and what would the timeline be?

**Comment by makasim** [comment]
@afilina Thank you for the offer but it is a bit too late for me. I don't use PHP much these days. Maybe someone else would like to pick this up. I don't mind.

**Comment by afilina** [comment]
Could this issue at least be reopened? It really hit me hard out of nowhere.
