### ISSUE TITLE
Error in new version enqueue-bundle "Attempted to load class "DoctrineSchemaCompilerPass"

### ISSUE THREAD

**Issue by powerpd** [php-enqueue/enqueue-dev#761]
I got error after update enqueue to 0.9.7
composer.json
```
        "enqueue/dbal": "^0.9.7",
        "enqueue/enqueue-bundle": "^0.9.7",
```

Error
```
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineSchemaCompilerPass" from namespace "Enqueue\Doctrine".
!!  Did you forget a "use" statement for another namespace? in /var/www/site/vendor/enqueue/enqueue-bundle/EnqueueBundle.php:44
!!  Stack trace:
!!  #0 /var/www/site/vendor/symfony/http-kernel/Kernel.php(679): Enqueue\Bundle\EnqueueBundle->build(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
!!  #1 /var/www/site/vendor/symfony/http-kernel/Kernel.php(651): Symfony\Component\HttpKernel\Kernel->prepareContainer(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
!!  #2 /var/www/site/vendor/symfony/http-kernel/Kernel.php(543): Symfony\Component\HttpKernel\Kernel->buildContainer()
!!  #3 /var/www/site/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
!!  #4 /var/www/site/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Component\HttpKernel\Kernel->boot()
!!  #5 /var/www/site/vendor/symfony/con in /var/www/site/vendor/enqueue/enqueue-bundle/EnqueueBundle.php on line 44
```

**Comment by makasim** [comment]
You should upgrade `enqueue\enqueue` to `0.9.7`

**Comment by powerpd** [comment]
Thanks, got it, I'll try at evening and write here about results :)

**Comment by powerpd** [comment]
Yeah, my mistake, sorry for troubling
