### ISSUE TITLE
[gps] Invalid pubsub messages should be acknowledged to avoid requeued

### ISSUE THREAD

**Issue by gjanvier** [php-enqueue/enqueue-dev#830]
Hello,

I am using enqueue/gps (0.9.2) for Google PubSub, and during my tests, when I submit an invalid message in the topic (manually, or with a different application), I got this error.

```
InvalidArgumentException: The malformed json given. Error 4 and message Syntax error (uncaught exception) at 
/var/www/html/vendor/enqueue/gps/GpsMessage.php line 161 while running console command `messenger:consume-messages` 
{"exception":"[object] (InvalidArgumentException(code: 0): The malformed json given. Error 4 and message Syntax error at 
/var/www/html/vendor/enqueue/gps/GpsMessage.php:161)",
"trace":"#0 /var/www/html/vendor/enqueue/gps/GpsConsumer.php(113): Enqueue\\Gps\\GpsMessage::jsonUnserialize('truc')
#1 /var/www/html/vendor/enqueue/gps/GpsConsumer.php(130): Enqueue\\Gps\\GpsConsumer->convertMessage(Object(Google\\Cloud\\PubSub\\Message))
#2 /var/www/html/vendor/enqueue/gps/GpsConsumer.php(57): Enqueue\\Gps\\GpsConsumer->receiveMessage(30)
#3 /var/www/html/vendor/enqueue/messenger-adapter/QueueInteropTransport.php(75): Enqueue\\Gps\\GpsConsumer->receive(30000)
#4 /var/www/html/vendor/symfony/messenger/Worker.php(50): Enqueue\\MessengerAdapter\\QueueInteropTransport->receive(Object(Closure))
#5 /var/www/html/vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(159): Symfony\\Component\\Messenger\\Worker->run()
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(255): Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#7 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(971): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#8 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(86): Symfony\\Component\\Console\\Application->doRunCommand(Object(Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(248): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRunCommand(Object(Symfony\\Component\\Messenger\\Command\\ConsumeMessagesCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(74): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\\Bundle\\FrameworkBundle\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/www/html/bin/console(28): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput))
#13 {main}"} []
```

Basically we can have a bad situation in the `GpsConsumer` if a message has an issue, as such message would keep being pulled, generating an exception, being requeued and re-pulled, generating an exception...

```php
// https://github.com/php-enqueue/gps/blob/master/GpsConsumer.php#L111
    private function convertMessage(GoogleMessage $message): GpsMessage
    {
        $gpsMessage = GpsMessage::jsonUnserialize($message->data()); // raises an InvalidArgumentException
        $gpsMessage->setNativeMessage($message);
        return $gpsMessage;
    }
```

I think we would need to handle this error and make sure that such message is definitely acknowledged ?

**Comment by makasim** [comment]
This can lead to bad situations when a problem goes unnoticed. The issue should be addressed on a higher level, not in the consumer). For example, a consumer extension can handle an exception and reject the message. I would go that way If I needed it.
